### ISSUE TITLE
Should we merge reduxSwift-rx with this

### ISSUE THREAD

**Issue by Aleksion** [ReSwift/ReduxRxSwift#1]

**Comment by agentk** [comment]
That's a good idea. I was also thinking about adding a create-createStore that also exposes the underlying Variable<State> to enable simple path selecting. Ie. `let isAuthed: Variable<Bool> = state.map { $0.auth.isAuthed }`

**Comment by agentk** [comment]
Added in 0.1.4. Let me know if I've missed anything.
