### ISSUE TITLE
Cartfile still points to "agentk/reduxSwift" instead of "ReduxKit/ReduxKit" 

### ISSUE THREAD

**Issue by waveyus** [ReSwift/ReduxRxSwift#3]

**Comment by agentk** [comment]
Got that in my sights as we speak :-)

**Comment by waveyus** [comment]
Thanks! : - )
Several other projects shared the same issue, like ReduxKitRouter, etc.
Also, those still use `Import Redux` or `import SwiftRedux` import statements

**Comment by agentk** [comment]
Updating for this project is now done. Also note the framework modules will all be named the same as the github projects now. Ie, @import ReduxRx will now be @import ReduxKitRxSwift. It's a bit more verbose, but clearer. There is the observable middleware I'll merge into this project, then I'll update the other bindings and release the cocoapods.

**Comment by waveyus** [comment]
Thanks!
